version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
    working_directory: ~/mapbox-gl-js
    steps:
      - checkout
      - run: yarn
      - run: yarn run test-expressions
      - store_artifacts:
          path: test/integration/expression-tests/index.html
          destination: expression-tests/index.html
      - run: yarn run lint
      - run: yarn run test-unit
      - run:
          name: If on master, build the project
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then yarn run build-prod;
            fi
      - run:
          name: If on master, deploy to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then yarn run deploy;
            fi
